services:
  tests:
    build: .
    environment:
      CONSUL_HTTP_ADDR: http://consul:8500
    depends_on:
      consul:
        condition: service_healthy
#    networks:
#      default:
#        ipv4_address: 192.168.80.3

  consul:
    image: consul
    expose:
      - "8500"
      - "8600"
      - "8300"
    command: "agent -server -bootstrap -dev -bind=0.0.0.0 -client 0.0.0.0 -node consul"
    healthcheck:
      test: ["CMD", "curl", "http://localhost:8500/v1/agent/checks"]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 5s

networks:
  default:
#    ipam:
#      driver: default
#      config:
#        - subnet: 192.168.0.0/16
